import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { geoMercator, geoPath } from 'd3-geo'

type Topic={id:string;label:string;color:string}
type Daily={date:string;source:'gdelt_ngrams'|'bluesky'|'google_trends';topic_id:string;measure:string;value:number|null;unit:string;denominator?:number;denominator_definition:string;completeness?:number;metadata?:Record<string,unknown>}
type Article={article_id:string;title:string|null;url:string;published_at:string;outlet_domain:string|null;topic_id:string;phrase_evidence:string[]}
type Physical={observed_at:string;metric:string;value:number|null;unit:string;baseline_start_year?:number;baseline_end_year?:number;valid_area_fraction?:number}
type Event={event_id:string;source:string;event_type:string;name:string;start_at:string;end_at?:string|null;alert_level?:string|null;geometry?:{coordinates?:number[]}}
type LayerDef={layer_id:string;label:string;provider:string;cadence:string;geography:string;units:string[];status:'fixture_ready'|'adapter_ready'|'access_pending'|'deferred'}
type LayerObs={source:string;series_id?:string;observed_at?:string;unit?:string;quality_status:string;value:number|null}
type Release={release:{release_id:string;created_at:string;date_start:string;date_end:string;configuration_version:string;status:string;methodology_note:string};daily_attention:Daily[];news_denominators:{date:string;captured_article_count:number}[];articles:Article[];social_posts:{post_id:string;handle:string;posted_at:string;text:string|null;topic_ids:string[]}[];physical_observations:Physical[];events:Event[];data_layers?:LayerObs[];layer_definitions?:LayerDef[];metadata:{panel_definition:string;article_denominator:string}}
type GeoJson={type:'FeatureCollection';features:any[]}
type View='timeline'|'map'|'saved'|'data'|'methods'
type PlotType='lines'|'layers'
type LayerSourceId='news'|'social'|'political'|'search'
const TOPICS:Topic[]=[{id:'climate_change',label:'Climate change',color:'#1d7458'},{id:'clean_transport',label:'Clean transport',color:'#4d84b7'},{id:'cost_of_living',label:'Cost of living',color:'#d9904b'},{id:'electric_vehicles',label:'Electric vehicles',color:'#7b6ab0'}]
const topicMap=Object.fromEntries(TOPICS.map(topic=>[topic.id,topic])) as Record<string,Topic>
const LAYER_OPTIONS=[
  {id:'news',label:'News',source:'gdelt_ngrams',description:'Captured UK news',status:'available'},
  {id:'social',label:'Social',source:'bluesky',description:'Monitored social posts',status:'available'},
  {id:'political',label:'Political',source:'political_signals',description:'Policy and institutional action',status:'pending'},
  {id:'search',label:'Search',source:'google_trends',description:'Online search interest',status:'pending'},
] as const
const layerOptionMap=Object.fromEntries(LAYER_OPTIONS.map(option=>[option.id,option])) as Record<LayerSourceId,(typeof LAYER_OPTIONS)[number]>
const fmtDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value.slice(0,10)}T00:00:00Z`))
const pct=(value:number|null|undefined)=>value==null?'—':`${(value*100).toFixed(2)}%`
function readState(){const p=new URLSearchParams(location.search);const selected=p.get('topics')?.split(',').filter(id=>topicMap[id]);const selectedLayers=(p.get('layers')?.split(',').filter(id=>LAYER_OPTIONS.some(option=>option.id===id))||[]) as LayerSourceId[];return{topics:selected?.length?selected:['climate_change','clean_transport'],layerSources:selectedLayers.length?selectedLayers:['news'] as LayerSourceId[],channel:p.get('channel')||'gdelt_ngrams',start:p.get('start')||'2026-08-01',end:p.get('end')||'2026-08-30',geography:p.get('geography')||'GB',granularity:p.get('granularity')||'daily',measure:p.get('measure')||'share',events:p.get('events')||'all',smooth:p.get('smooth')!=='0',plot:(p.get('plot')==='layers'?'layers':'lines') as PlotType}}
const routeFor=(view:View)=>view==='saved'?'/views':`/${view}`
const viewFromPath=():View=>{const path=location.pathname.split('/')[1];return path==='map'||path==='data'||path==='methods'||path==='views'?(path==='views'?'saved':path):'timeline'}
function App(){
  const [release,setRelease]=useState<Release|null>(null)
  const [view,setView]=useState<View>(viewFromPath)
  const [state,setState]=useState(readState)
  const [article,setArticle]=useState<Article|null>(null)
  useEffect(()=>{fetch('/data/release.json').then(response=>response.json()).then(setRelease)},[])
  useEffect(()=>{const back=()=>{setView(viewFromPath());setState(readState())};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[])
  useEffect(()=>{const params=new URLSearchParams(location.search);params.set('topics',state.topics.join(','));params.set('layers',state.layerSources.join(','));params.set('channel',state.channel);params.set('start',state.start);params.set('end',state.end);params.set('geography',state.geography);params.set('granularity',state.granularity);params.set('measure',state.measure);params.set('events',state.events);params.set('smooth',state.smooth?'1':'0');params.set('plot',state.plot);history.replaceState(null,'',`${routeFor(view)}?${params}`)},[state,view])
  const update=(partial:Partial<typeof state>)=>setState(current=>({...current,...partial}))
  const navigate=(next:View)=>{history.pushState(null,'',`${routeFor(next)}${location.search}`);setView(next)}
  if(!release)return <div className="atlas-app"><main className="atlas-content"><strong>Loading UK Attention Atlas…</strong></main></div>
  return <div className="atlas-app">
    <header className="atlas-topbar"><button className="atlas-brand" onClick={()=>navigate('timeline')}><span className="atlas-brand-mark">A</span><span>UK Attention Atlas</span></button><nav className="atlas-nav" aria-label="Primary navigation">{([['timeline','Timeline'],['map','UK map'],['saved','Saved views'],['data','Data'],['methods','Methods']] as const).map(([id,label])=><button key={id} type="button" aria-selected={view===id} onClick={()=>navigate(id)}>{label}</button>)}</nav><div className="atlas-status"><i/> Release {release.release.release_id}</div></header>
    {view==='timeline'&&<Timeline release={release} state={state} update={update} onArticle={setArticle}/>}
    {view==='map'&&<MapView release={release} state={state} update={update} onTimeline={()=>navigate('timeline')}/>}
    {view==='saved'&&<SavedView onOpen={url=>{history.pushState(null,'',url);setState(readState());setView(viewFromPath())}}/>}
    {view==='data'&&<DataView release={release}/>}
    {view==='methods'&&<MethodsView release={release}/>}
    {article&&<ArticleDrawer article={article} onClose={()=>setArticle(null)}/>}
  </div>
}
function Header({title,subtitle,release}:{title:string;subtitle:string;release:Release}){return <div className="atlas-heading"><div><h1>{title}</h1><p className="atlas-subtitle">{subtitle}</p></div><div className="atlas-actions"><button className="atlas-action" type="button" onClick={()=>saveView(title,release)}>Save view</button><button className="atlas-action" type="button" onClick={()=>navigator.clipboard?.writeText(location.href)}>Share</button><button className="atlas-action atlas-primary" type="button" onClick={()=>download(release)}>Export</button></div></div>}
function buildRows(release:Release,state:ReturnType<typeof readState>,sources:string[]){
  const map=new Map<string,Record<string,number|string>>();
  release.daily_attention.filter(row=>state.topics.includes(row.topic_id)&&row.date>=state.start&&row.date<=state.end&&sources.includes(row.source)).forEach(row=>{
    const item=map.get(row.date)||{date:row.date};
    item[`${row.source}_${row.topic_id}`]=state.measure==='count'?Number(row.metadata?.[row.source==='bluesky'?'raw_post_count':'raw_article_count']??NaN):(row.value??NaN);
    map.set(row.date,item)
  });
  (release.data_layers||[]).filter(layer=>layer.source==='desnz_fuel_prices'&&layer.series_id==='uk_petrol'&&layer.observed_at&&layer.observed_at>=state.start&&layer.observed_at<=state.end).forEach(layer=>{
    const day=layer.observed_at!;const item=map.get(day)||{date:day};item.petrol=layer.value??NaN;map.set(day,item)
  });
  return[...map.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)))
}
function Timeline({release,state,update,onArticle}:{release:Release;state:ReturnType<typeof readState>;update:(partial:Partial<ReturnType<typeof readState>>)=>void;onArticle:(article:Article)=>void}){
  const rows=useMemo(()=>buildRows(release,state,[state.channel]),[release,state]);
  const layerRows=useMemo(()=>buildRows(release,state,state.layerSources.map(id=>layerOptionMap[id].source)),[release,state]);
  const latest=release.daily_attention.filter(row=>row.source===state.channel&&row.topic_id===state.topics[0]&&row.date>=state.start&&row.date<=state.end).at(-1);
  const den=release.news_denominators.at(-1);
  const eventList=state.events==='none'?[]:release.events;
  const periodDays=(new Date(state.end).getTime()-new Date(state.start).getTime())/86400000+1;
  const toggleLayer=(id:LayerSourceId)=>{const option=layerOptionMap[id];if(option.status==='pending')return;const next:LayerSourceId[]=state.layerSources.includes(id)?state.layerSources.filter(value=>value!==id):[...state.layerSources,id];if(next.length)update({layerSources:next})};
  return <main className="atlas-content">
    <Header title="Attention timeline" subtitle="Compare attention and context across the UK" release={release}/>
    <section className="atlas-visualisation-picker" aria-label="Visualisation picker"><div><span className="atlas-eyebrow">Visualisation</span><strong>{state.plot==='lines'?'Multi-series lines':'Layered relative intensity'}</strong></div><div className="atlas-plot-switch" role="group" aria-label="Plot type"><button type="button" className={state.plot==='lines'?'active':''} aria-pressed={state.plot==='lines'} onClick={()=>update({plot:'lines'})}>Lines</button><button type="button" className={state.plot==='layers'?'active':''} aria-pressed={state.plot==='layers'} onClick={()=>update({plot:'layers'})}>Layered bands</button></div></section>
    <section className="atlas-controls">
      <div className="atlas-control-row"><span className="atlas-control-label">Topics</span>{TOPICS.map(topic=><button key={topic.id} className={`atlas-chip ${state.topics.includes(topic.id)?'active':''}`} type="button" onClick={()=>update({topics:state.topics.includes(topic.id)?state.topics.filter(id=>id!==topic.id):[...state.topics,topic.id]})}>{topic.label}{state.topics.includes(topic.id)&&' ×'}</button>)}<button className="atlas-chip" type="button" onClick={()=>update({topics:TOPICS.map(topic=>topic.id)})}>+ Add topic</button></div>
      <div className="atlas-control-row"><span className="atlas-control-label">Compare</span>{[['gdelt_ngrams','News'],['google_trends','Search'],['bluesky','Social']].map(([id,label])=><button key={id} className={`atlas-chip ${state.channel===id?'active':''}`} type="button" disabled={id==='google_trends'} onClick={()=>id!=='google_trends'&&update({channel:id})}>{label}{id==='google_trends'?' · pending':''}</button>)}<select className="atlas-select" aria-label="Geography" value={state.geography} onChange={event=>update({geography:event.target.value})}><option value="GB">United Kingdom</option><option value="ENG" disabled>England · unavailable</option><option value="LON" disabled>Greater London · unavailable</option></select><select className="atlas-select" aria-label="Granularity" value={state.granularity} onChange={event=>update({granularity:event.target.value})}><option value="daily">Daily</option><option value="weekly" disabled>Weekly · planned</option><option value="monthly" disabled>Monthly · planned</option></select><label className="atlas-date-label">From <input className="atlas-select" type="date" value={state.start} min={release.release.date_start} max={state.end} onChange={event=>update({start:event.target.value})}/></label><label className="atlas-date-label">To <input className="atlas-select" type="date" value={state.end} min={state.start} max={release.release.date_end} onChange={event=>update({end:event.target.value})}/></label><select className="atlas-select" aria-label="Attention measure" value={state.measure} onChange={event=>update({measure:event.target.value})}><option value="share">Share (%)</option><option value="count">Raw count</option></select></div>
    </section>
    {state.plot==='lines'&&<section className="atlas-builder" aria-label="Chart series builder"><Axis title={`Left Y axis · ${state.measure==='share'?'Attention share (%)':'Raw count'}`} color="green" topics={state.topics} channel={state.channel} measure={state.measure}/><Axis title="Right Y axis · Petrol price (p/litre)" color="orange" topics={['desnz_fuel_prices']} right/></section>}
    <div className="atlas-events"><span className="atlas-events-label">X-axis events</span>{eventList.map(event=><button key={event.event_id} className="atlas-event-chip active" type="button">{event.name}</button>)}<button className="atlas-event-chip" type="button" onClick={()=>update({events:state.events==='none'?'all':'none'})}>{state.events==='none'?'Show events':'Hide events'}</button><button className="atlas-chip" type="button" disabled title="Custom reviewed events will be added to saved views">+ Custom event · planned</button></div>
    {state.plot==='layers'&&<section className="atlas-layer-controls" aria-label="Layered plot controls"><div className="atlas-layer-controls-head"><div><span className="atlas-eyebrow">Layer selection</span><strong>Choose signal families and topics</strong></div><span className="atlas-layer-count">{state.layerSources.length} family{state.layerSources.length===1?'':'ies'} · {state.topics.length} topic{state.topics.length===1?'':'s'}</span></div><div className="atlas-layer-family-list">{LAYER_OPTIONS.map(option=><button key={option.id} type="button" className={`atlas-layer-choice ${state.layerSources.includes(option.id)?'active':''} ${option.status==='pending'?'pending':''}`} aria-pressed={state.layerSources.includes(option.id)} disabled={option.status==='pending'} onClick={()=>toggleLayer(option.id)}><span className="atlas-layer-choice-dot" style={{background:option.id==='social'?'#a249a5':option.id==='political'?'#3e4c78':option.id==='search'?'#168a7d':'#1d7458'}}/><span><b>{option.label}</b><small>{option.status==='pending'?'Pending source access':option.description}</small></span></button>)}</div><div className="atlas-layer-topic-list"><span>Topics</span>{TOPICS.map(topic=><button key={topic.id} type="button" className={`atlas-layer-topic ${state.topics.includes(topic.id)?'active':''}`} aria-pressed={state.topics.includes(topic.id)} onClick={()=>update({topics:state.topics.includes(topic.id)?state.topics.filter(id=>id!==topic.id):[...state.topics,topic.id]})}><i style={{background:topic.color}}/>{topic.label}</button>)}</div><p className="atlas-layer-help">Click a band in the chart to inspect it. Political and search layers are reserved in this release until their approved feeds are connected.</p></section>}
    <div className="atlas-measures"><Measure label="Chart title" value="Climate and context" color="green"/><Measure label="Appearance" value="Customize" color="blue"/><Measure label="Metric builder" value={`${state.topics.length} metrics`} color="purple"/><Measure label="Coverage" value={`${rows.length} of ${periodDays} days`} color="orange"/></div>
    <section className="atlas-chart-shell">
      <div className="atlas-chart-title"><span>{state.plot==='layers'?'Selected attention layers':state.channel==='bluesky'?'Posts from monitored Bluesky accounts':'Captured GDELT UK news'} · {state.measure==='count'?'raw count':'share'}</span><span>{fmtDate(state.start)} – {fmtDate(state.end)} · {state.granularity}</span></div>
      <div className={`atlas-chart-plot ${state.plot==='layers'?'atlas-layered-plot':''}`}>
        {state.plot==='lines'?<ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:8,right:10,left:0,bottom:0}}><CartesianGrid stroke="#e4ece7" vertical={false}/><XAxis dataKey="date" tickFormatter={value=>fmtDate(String(value)).slice(0,6)} tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickFormatter={value=>state.measure==='share'?`${(Number(value)*100).toFixed(1)}%`:String(value)} tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickFormatter={value=>`${Number(value).toFixed(0)}p`} tickLine={false} axisLine={false}/><Tooltip labelFormatter={value=>fmtDate(String(value))} formatter={(value:unknown,name:unknown)=>[typeof value==='number'?(name==='Petrol price'?`${value.toFixed(1)} p/litre`:state.measure==='share'?pct(value):`${value.toFixed(0)} ${state.channel==='bluesky'?'posts':'articles'}`):'—',String(name)]} contentStyle={{border:'1px solid #d9e4df',borderRadius:6,fontSize:11}}/>{eventList.map(event=><ReferenceLine key={event.event_id} x={event.start_at.slice(0,10)} stroke="#d9904b" strokeDasharray="4 3"/>)}{state.topics.map(id=><Line yAxisId="left" key={id} dataKey={`${state.channel}_${id}`} name={topicMap[id]?.label||id} stroke={topicMap[id]?.color||'#1d7458'} strokeWidth={2} dot={false} connectNulls={!state.smooth}/>)}<Line yAxisId="right" dataKey="petrol" name="Petrol price" stroke="#d9904b" strokeWidth={2} dot={false} connectNulls={false}/></LineChart></ResponsiveContainer>:<LayeredPlot rows={layerRows} topics={state.topics} layerSources={state.layerSources} events={eventList}/>}</div>
      {state.plot==='lines'?<div className="atlas-chart-caption">{state.topics.map(id=><span key={id}><i className="atlas-legend-dot" style={{background:topicMap[id].color}}/>{topicMap[id].label}</span>)}<span><i className="atlas-legend-dot" style={{background:'#d9904b'}}/>Petrol price · right axis</span><span>Gaps remain visible; missing days are not zeros</span></div>:<div className="atlas-chart-caption"><span><i className="atlas-layered-key"/>Band thickness: relative intensity within each selected layer</span><span>Each layer is scaled to its own peak; overlap is exploratory, not causal</span></div>}
    </section>
    <section className="atlas-evidence"><article className="atlas-evidence-card"><span className="atlas-eyebrow">Selected period · {fmtDate(state.start)} – {fmtDate(state.end)}</span><h2>{topicMap[state.topics[0]]?.label||'Topic'} attention is {pct(latest?.value)}</h2><p>{state.channel==='bluesky'?`${Number(latest?.metadata?.raw_post_count||0)} matching posts from ${latest?.denominator||0} monitored-panel posts.`:`${Number(latest?.metadata?.raw_article_count||0)} matching URLs from ${latest?.denominator||den?.captured_article_count||0} captured UK articles.`} The period uses configuration {release.release.configuration_version}.</p></article><article className="atlas-evidence-card"><span className="atlas-eyebrow">Article evidence</span><div className="atlas-article-list">{release.articles.filter(article=>state.topics.includes(article.topic_id)).slice(0,4).map(article=><button className="atlas-article" key={article.article_id} type="button" onClick={()=>onArticle(article)}><span>{article.title}</span><small>{article.outlet_domain} · {fmtDate(article.published_at)}</small></button>)}</div></article></section>
    <p className="atlas-chart-caption">Associations and timing are exploratory. News, social, search and physical measures retain separate units and denominators.</p>
  </main>
}
function LayeredPlot({rows,topics,layerSources,events}:{rows:Record<string,number|string>[];topics:string[];layerSources:LayerSourceId[];events:Event[]}){
  const [selectedBand,setSelectedBand]=useState<string|null>(null)
  const [hoveredBand,setHoveredBand]=useState<string|null>(null)
  const series=layerSources.flatMap(sourceId=>topics.map(topicId=>({id:`${sourceId}:${topicId}`,key:`${layerOptionMap[sourceId].source}_${topicId}`,sourceId,topicId,label:`${layerOptionMap[sourceId].label} · ${topicMap[topicId]?.label||topicId}`,color:topicMap[topicId]?.color||'#1d7458'}))).filter(item=>rows.some(row=>typeof row[item.key]==='number'&&Number.isFinite(row[item.key])))
  if(!series.length)return <div className="atlas-layered-empty"><strong>No observed data for this selection yet.</strong><span>Choose News or Social and at least one topic above.</span></div>
  const width=1320;
  const left=278;
  const right=26;
  const top=34;
  const bottom=36;
  const laneHeight=series.length>6?52:series.length>4?60:72;
  const height=top+bottom+laneHeight*series.length;
  const plotWidth=width-left-right;
  const xFor=(index:number)=>left+(rows.length<=1?0:(index/(rows.length-1))*plotWidth);
  const valueFor=(row:Record<string,number|string>,key:string)=>{const value=row[key];return typeof value==='number'&&Number.isFinite(value)?value:null};
  const smoothPath=(points:[number,number][],start:'M'|'L'='M')=>{if(!points.length)return '';let d=`${start} ${points[0][0]} ${points[0][1]}`;for(let index=1;index<points.length;index++){const [x0,y0]=points[index-1];const [x1,y1]=points[index];const mid=(x0+x1)/2;d+=` C ${mid} ${y0}, ${mid} ${y1}, ${x1} ${y1}`}return d};
  const eventX=(date:string)=>{const index=rows.findIndex(row=>String(row.date)===date);if(index<0)return null;return xFor(index)};
  const activate=(id:string)=>setSelectedBand(current=>current===id?null:id);
  const activeBand=hoveredBand||selectedBand;
  return <svg className="atlas-layered-svg" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Selectable layered relative intensity bands for the selected attention series" preserveAspectRatio="xMidYMid meet">
    <g className="atlas-layered-events">{events.map((event,eventIndex)=>{const startX=eventX(event.start_at.slice(0,10));const endX=eventX((event.end_at||event.start_at).slice(0,10));if(startX==null)return null;const x=Math.max(left,startX-12);const x2=Math.min(width-right,endX==null?startX+28:endX+12);return <g key={event.event_id}><rect x={x} y={16} width={Math.max(18,x2-x)} height={height-bottom-8} rx={6}/><text x={x+6} y={27+(eventIndex%3)*12}>{event.name}</text></g>})}</g>
    {series.map((item,layerIndex)=>{
      const values=rows.map(row=>valueFor(row,item.key));
      const observed=values.filter((value):value is number=>value!=null);
      const min=Math.min(...observed);
      const max=Math.max(...observed);
      const center=top+laneHeight*layerIndex+laneHeight/2;
      const thickness=(value:number|null)=>value==null?3:7+(max===min?0.6:((value-min)/(max-min))*20);
      const bandTop=values.map((value,index)=>[xFor(index),center-thickness(value)] as [number,number]);
      const bandBottom=values.map((value,index)=>[xFor(index),center+thickness(value)] as [number,number]);
      const area=`${smoothPath(bandTop)} ${smoothPath([...bandBottom].reverse(),'L')} Z`;
      const source=layerOptionMap[item.sourceId];
      const isMuted=activeBand!=null&&activeBand!==item.id;
      return <g key={item.id} className={`atlas-layered-band ${selectedBand===item.id?'selected':''}`} opacity={isMuted?.24:1} role="button" tabIndex={0} aria-label={`Select ${item.label}`} aria-pressed={selectedBand===item.id} onClick={()=>activate(item.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();activate(item.id)}}} onMouseEnter={()=>setHoveredBand(item.id)} onMouseLeave={()=>setHoveredBand(null)}><rect className="atlas-layered-lane" x={8} y={center-laneHeight/2+3} width={width-16} height={laneHeight-6} rx={8} fill={item.color}/><line className="atlas-layered-center" x1={left} x2={width-right} y1={center} y2={center}/><path d={area} fill={item.color} fillOpacity={0.3} stroke={item.color} strokeWidth={activeBand===item.id?3:2}/><circle className="atlas-layered-source-dot" cx={18} cy={center-4} r={4} fill={source.id==='social'?'#a249a5':'#1d7458'}/><text className="atlas-layered-label" x={30} y={center+1}>{item.label}</text><text className="atlas-layered-subtitle" x={30} y={center+16}>{source.description} · scaled within selection</text><title>{item.label}: click to highlight this layer</title></g>
    })}
    <line className="atlas-layered-axis" x1={left} x2={width-right} y1={height-bottom+3} y2={height-bottom+3}/>{[0,.5,1].map((position,index)=>{const x=left+plotWidth*position;const row=rows[Math.min(rows.length-1,Math.round((rows.length-1)*position))];return <g key={position}><line className="atlas-layered-tick" x1={x} x2={x} y1={height-bottom+3} y2={height-bottom+9}/><text className="atlas-layered-date" x={x} y={height-9} textAnchor={index===0?'start':index===2?'end':'middle'}>{row?fmtDate(String(row.date)):''}</text></g>})}</svg>
}
function Axis({title,color,topics,right=false,channel='gdelt_ngrams',measure='share'}:{title:string;color:string;topics:string[];right?:boolean;channel?:string;measure?:string}){return <div className={`atlas-axis ${right?'right':''}`}><div className="atlas-axis-head"><span>{title}</span><button type="button">Edit</button></div>{topics.slice(0,right?1:4).map((id,index)=><div className="atlas-series" key={id}><i style={{background:right?'#d9904b':topicMap[id]?.color||'#1d7458'}}/><span>{right?'Petrol · fixture p/litre':`${topicMap[id]?.label||id} · ${channel==='bluesky'?'monitored posts':'UK news'} ${measure}`}</span><small>•••</small></div>)}<button className="atlas-add" type="button" disabled title="Select topics above to change series">+ Add series via Topics</button></div>}
function Measure({label,value,color}:{label:string;value:string;color:string}){return <button className="atlas-measure" type="button"><span><b style={{background:`var(--atlas-${color})`}}/>{label}</span><strong>{value}</strong></button>}
function MapView({release,state,update,onTimeline}:{release:Release;state:ReturnType<typeof readState>;update:(partial:Partial<ReturnType<typeof readState>>)=>void;onTimeline:()=>void}){
  const [geo,setGeo]=useState<GeoJson|null>(null)
  const [mapDay,setMapDay]=useState(state.start)
  const [playing,setPlaying]=useState(false)
  const [step,setStep]=useState(1)
  const [speed,setSpeed]=useState(1)
  const [layer,setLayer]=useState<'attention'|'ndvi'|'events'>('attention')
  const [selectedPlace,setSelectedPlace]=useState('United Kingdom')
  useEffect(()=>{fetch('/data/uk-admin1.geojson').then(response=>response.json()).then(setGeo)},[])
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setMapDay(day=>{const next=shiftDay(day,step);if(next>state.end){setPlaying(false);return day}return next}),1000/speed);return()=>window.clearInterval(timer)},[playing,speed,step,state.end])
  const projection=useMemo(()=>geo?geoMercator().fitSize([820,520],geo):null,[geo])
  const path=projection?geoPath(projection):null
  const dayIndex=Math.max(0,Math.round((new Date(mapDay).getTime()-new Date(state.start).getTime())/86400000))
  const dayCount=Math.max(1,Math.round((new Date(state.end).getTime()-new Date(state.start).getTime())/86400000))
  const news=release.daily_attention.find(row=>row.date===mapDay&&row.topic_id==='climate_change'&&row.source==='gdelt_ngrams')
  // MODIS MOD13C2 is monthly. Resolve the selected day to its month so a
  // value from another month can never be shown as if it were daily data.
  const ndviPeriod=mapDay.slice(0,7)
  const ndvi=release.physical_observations.find(row=>row.metric==='ndvi_anomaly'&&row.observed_at.slice(0,7)===ndviPeriod)
  const events=release.events.filter(event=>event.start_at.slice(0,10)<=mapDay&&(event.end_at?.slice(0,10)||event.start_at.slice(0,10))>=mapDay).map(event=>{const coordinates=event.geometry?.coordinates;const point=coordinates&&projection?projection([coordinates[0],coordinates[1]]):null;return{...event,point}})
  const localUnavailable=selectedPlace!=='United Kingdom'
  const selectLayer=(next:typeof layer)=>{setLayer(next);setPlaying(false)}
  const changeDay=(next:string)=>{setMapDay(next);setPlaying(false)}
  return <main className="atlas-content">
    <Header title="UK map" subtitle="Place, event and attention patterns" release={release}/>
    <div className="atlas-map-layout">
      <aside className="atlas-map-panel"><h2>Layers</h2><LayerGroup title="Attention"><button className={`atlas-layer ${layer==='attention'?'active':''}`} type="button" onClick={()=>selectLayer('attention')}><span style={{background:'var(--atlas-green)'}}/>Climate change news share</button><LayerButton label="Clean transport · UK only"/><LayerButton label="Cost of living · UK only"/></LayerGroup><LayerGroup title="Physical"><button className={`atlas-layer ${layer==='ndvi'?'active':''}`} type="button" onClick={()=>selectLayer('ndvi')}><span style={{background:'var(--atlas-purple)'}}/>MODIS NDVI · UK only</button><LayerButton label="Temperature · pending"/></LayerGroup><LayerGroup title="Events"><button className={`atlas-layer ${layer==='events'?'active':''}`} type="button" onClick={()=>selectLayer('events')}><span style={{background:'var(--atlas-orange)'}}/>GDACS / FIRMS</button><LayerButton label="Policy · pending"/></LayerGroup></aside>
      <div className="atlas-map-canvas" aria-label="Detailed UK administrative boundary map">{!geo&&<div className="atlas-map-loading">Loading UK administrative boundaries…</div>}{geo&&projection&&path&&<svg viewBox="0 0 820 520"><g>{geo.features.map((feature:any,index:number)=>{const name=feature.properties?.name_en||feature.properties?.name||'Administrative area';return <path key={`${name}-${index}`} d={path(feature)||undefined} className={`uk-region ${selectedPlace===name?'selected':''}`} onClick={()=>setSelectedPlace(name)} tabIndex={0} role="button" aria-label={`Select ${name}`} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelectedPlace(name)}}}><title>{name}</title></path>})}</g>{layer==='events'&&events.map(event=>event.point&&<g className="map-event-marker" key={event.event_id} transform={`translate(${event.point[0]},${event.point[1]})`}><circle r="8"/><circle r="3"/><title>{event.name}</title></g>)}</svg>}<button className="atlas-map-reset" type="button" onClick={()=>setSelectedPlace('United Kingdom')}>View UK total</button></div>
      <aside className="atlas-map-detail"><span className="atlas-eyebrow">Selected place</span><h2>{selectedPlace}</h2><p>{fmtDate(mapDay)}</p><span className="atlas-detail-value">{localUnavailable?'Unavailable':layer==='attention'?pct(news?.value):layer==='ndvi'?(ndvi?.value==null?'—':`${ndvi.value.toFixed(2)} NDVI`):`${events.length} events`}</span><p>{localUnavailable?'Boundary shown for location only. Local attention and physical observations are not available in this release.':layer==='attention'?'Climate change share of captured GDELT UK news. National publishing geography; no county audience inference.':layer==='ndvi'?`MODIS country-scale monthly anomaly for ${ndviPeriod}; valid area ${Math.round((ndvi?.valid_area_fraction||0)*100)}%.`: 'Events active on this date; event points are separate from audience geography.'}</p><button className="atlas-detail-link" type="button" onClick={onTimeline}>Open in timeline →</button><button className="atlas-detail-link" type="button" onClick={()=>setSelectedPlace('United Kingdom')}>View source coverage →</button></aside>
    </div>
    <div className="atlas-map-time" aria-label="Map date controls"><button className="atlas-action" type="button" onClick={()=>changeDay(maxDay(state.start,shiftDay(mapDay,-step)))}>‹</button><button className="atlas-play" type="button" onClick={()=>setPlaying(value=>!value)}>{playing?'❚❚ Pause':'▶ Play'}</button><button className="atlas-action" type="button" onClick={()=>changeDay(minDay(state.end,shiftDay(mapDay,step)))}>›</button><input className="atlas-time-slider" type="range" min="0" max={dayCount} value={Math.min(dayCount,dayIndex)} aria-label="Map date timeline" onChange={event=>changeDay(shiftDay(state.start,Number(event.target.value)))}/><input className="atlas-select" type="date" aria-label="Map date" min={state.start} max={state.end} value={mapDay} onChange={event=>changeDay(event.target.value)}/><select className="atlas-select" aria-label="Map step" value={step} onChange={event=>setStep(Number(event.target.value))}><option value="1">Day</option><option value="7">Week</option><option value="30">Month</option></select><select className="atlas-select" aria-label="Map playback speed" value={speed} onChange={event=>setSpeed(Number(event.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></div>
    <div className="atlas-map-footer"><span>Map meaning: outlet location · article-mentioned place · event location</span><span>Current layer: {layer==='attention'?'GDELT news share':layer==='ndvi'?'MODIS NDVI anomaly':'GDACS/FIRMS events'} · release {release.release.release_id}</span></div>
  </main>
}
const shiftDay=(value:string,days:number)=>{const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
const minDay=(a:string,b:string)=>a<b?a:b
const maxDay=(a:string,b:string)=>a>b?a:b
function LayerGroup({title,children}:{title:string;children:ReactNode}){return <div className="atlas-layer-group"><strong>{title}</strong>{children}</div>}
function LayerButton({label,color,active=false}:{label:string;color?:string;active?:boolean}){return <button className={`atlas-layer ${active?'active':''}`} type="button"><span style={color?{background:`var(--atlas-${color})`}:undefined}/>{label}</button>}
type SavedSpec={id:string;title:string;url:string;releaseId:string;savedAt:string}
function getSavedViews():SavedSpec[]{try{return JSON.parse(localStorage.getItem('uk-atlas-views')||'[]')}catch{return[]}}
function saveView(title:string,release:Release){const saved=getSavedViews();saved.unshift({id:crypto.randomUUID(),title,url:location.pathname+location.search,releaseId:release.release.release_id,savedAt:new Date().toISOString()});localStorage.setItem('uk-atlas-views',JSON.stringify(saved));window.dispatchEvent(new Event('atlas-views-changed'))}
function SavedView({onOpen}:{onOpen:(url:string)=>void}){const [items,setItems]=useState(getSavedViews);useEffect(()=>{const update=()=>setItems(getSavedViews());window.addEventListener('atlas-views-changed',update);return()=>window.removeEventListener('atlas-views-changed',update)},[]);return <main className="atlas-content atlas-simple"><h1>Saved views</h1><p>Stored in this browser as reproducible analytical URLs.</p>{items.length===0&&<div className="atlas-evidence-card" style={{marginTop:20}}>Use “Save view” on the timeline or map to store the current date, topics, channel and geography.</div>}{items.map(item=><div className="atlas-saved-card" key={item.id}><div><strong>{item.title}</strong><small>{item.releaseId} · saved {fmtDate(item.savedAt)}</small></div><button type="button" onClick={()=>onOpen(item.url)}>Open →</button><button type="button" onClick={()=>{navigator.clipboard?.writeText(`${location.origin}${item.url}`)}}>Copy link</button><button type="button" onClick={()=>{localStorage.setItem('uk-atlas-views',JSON.stringify(items.filter(candidate=>candidate.id!==item.id)));setItems(getSavedViews())}}>Remove</button></div>)}</main>}
function DataView({release}:{release:Release}){const layers=release.layer_definitions||[];const observations=release.data_layers||[];return <main className="atlas-content atlas-simple"><Header title="Data" subtitle="Source coverage, freshness and access status" release={release}/><div className="atlas-evidence-card"><span className="atlas-eyebrow">Current dataset</span><h2>{release.release.release_id}</h2><p>{fmtDate(release.release.date_start)} – {fmtDate(release.release.date_end)} · configuration {release.release.configuration_version} · {release.release.status}</p></div><div className="atlas-source-status">{layers.map(layer=>{const rows=observations.filter(row=>row.source===layer.layer_id);const observed=rows.filter(row=>row.value!=null).length;return <article className="atlas-source-row" key={layer.layer_id}><i className={`atlas-source-dot ${layer.status==='access_pending'?'pending':layer.status==='adapter_ready'?'adapter':''}`}/><div><strong>{layer.label}</strong><small>{layer.provider} · {layer.cadence} · {layer.geography} · {layer.units.join(', ')}</small><small>{observed}/{rows.length} fixture rows with values · {layer.status.replace('_',' ')}</small></div></article>})}</div></main>}
function MethodsView({release}:{release:Release}){const layers=release.layer_definitions||[];const observations=release.data_layers||[];return <main className="atlas-content atlas-simple"><Header title="Data and methods" subtitle="Source contracts, coverage and research decisions" release={release}/><div className="atlas-method-grid"><Method title="GDELT Web NGrams" text="Topic matched distinct URLs divided by same-day captured GDELT UK news URLs." status="Fixture · BigQuery access pending"/><Method title="Bluesky monitored panel" text="Topic-matching posts divided by all posts from the monitored account panel." status="Seed panel · review required"/><Method title="MODIS MOD13C2" text="Monthly UK surface greenness anomaly against a 2001–2020 baseline." status="Imported fixture · refresh pending"/><Method title="Google Trends" text="Official API integration remains reserved for T&E access." status="Access pending"/></div><section className="atlas-evidence-card" style={{marginTop:12}}><span className="atlas-eyebrow">Source layer registry</span><h2>{observations.length} fixture observations across {layers.length} planned layers</h2><div className="atlas-source-status">{layers.map(layer=>{const count=observations.filter(row=>row.source===layer.layer_id).length;return <div className="atlas-source-row" key={layer.layer_id}><i className={`atlas-source-dot ${layer.status==='access_pending'?'pending':layer.status==='adapter_ready'?'adapter':''}`}/><div><strong>{layer.label}</strong><small>{layer.provider} · {layer.cadence} · {count} fixture rows</small></div><em>{layer.status.replace('_',' ')}</em></div>})}</div></section><div className="atlas-map-footer"><span>Release {release.release.release_id}</span><span>{release.release.methodology_note}</span></div></main>}
function Method({title,text,status}:{title:string;text:string;status:string}){return <article className="atlas-method-card"><h2>{title}</h2><p>{text}</p><small>{status}</small></article>}
function ArticleDrawer({article,onClose}:{article:Article;onClose:()=>void}){return <div className="atlas-drawer-backdrop" onClick={onClose}><aside className="atlas-article-drawer" onClick={event=>event.stopPropagation()}><button type="button" onClick={onClose}>×</button><span className="atlas-eyebrow">Article evidence</span><h2>{article.title}</h2><p>{article.outlet_domain} · {fmtDate(article.published_at)}</p><div className="atlas-evidence-card"><strong>Matched phrase</strong><p>“{article.phrase_evidence[0]}”</p></div><a href={article.url} target="_blank" rel="noreferrer">Open source URL ↗</a></aside></div>}
function download(release:Release){const blob=new Blob([JSON.stringify(release,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${release.release.release_id}.json`;anchor.click();URL.revokeObjectURL(url)}
export default App
